kind: pipeline
type: kubernetes
name: default

steps:

  - dependencies:
    image: node
    commands:
      - node -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn
    when:
      branch: master
      branch: develop

  

  - dependencies:
    image: node
    commands:
      - yarn build
    when:
      branch: master
      branch: develop


  - publish:
    image: node
    command: 
      - yarn publish
    when:
      event: tag
      branch: master
      branch: develop
