pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./.yarn-cache
      - ./node_modules
      - ./yarn.lock
    volumes:
      - /tmp/cache:/cache
    when:
      branch: master
      branch: develop

  dependencies:
    image: node
    commands:
      - node -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn
    when:
      branch: master
      branch: develop

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./.yarn-cache
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
    when:
      branch: develop

  dependencies:
    image: node
    commands:
      - yarn build
    when:
      branch: master
      branch: develop


  publish:
    image: node
    command: 
      - yarn publish
    when:
      event: tag
      branch: master
      branch: develop
